name: Push-to-Staging

# Trigger deployment only on push to staging branch
on:
  push:
    branches:
      - testing
jobs:
  BuildandpushtoECR:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key_id
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key
        aws configure set aws_access_key_id $(cat aws_access_key_id)
        aws configure set aws_secret_access_key $(cat aws_secret_access_key)
        aws configure set region eu-north-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 230374442770.dkr.ecr.eu-north-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -f ./web/Dockerfile -t nodejs-repo ./web/

    - name: Tag Docker image
      run: |
        docker tag nodejs-repo:latest 230374442770.dkr.ecr.eu-north-1.amazonaws.com/nodejs-repo:latest

    - name: Push Docker image to ECR
      run: |
        docker push 230374442770.dkr.ecr.eu-north-1.amazonaws.com/nodejs-repo:latest

  ssh-into-ansible-server:
    name: ssh-into-ansible-server
    runs-on: ubuntu-latest
    needs: BuildandpushtoECR
    steps:     
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 16.171.132.157
          username: ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |

            cd /home/ansible/Ansible/Deploy-NodeJS+MySQL
            ansible-playbook -i environment/inventory -e @vars/aws-cli.yml deploy-nodejs-PB.yml
            # ansible-playbook -i ../Mysql-Master-Slave/environment/master.yml -e @../Mysql-Master-Slave/vars/mysql-master-var.yml ../Mysql-Master-Slave/master-PB.yml
            # ansible-playbook -i ../Mysql-Master-Slave/environment/slave.yml -e @../Mysql-Master-Slave/vars/mysql-slave-var.yml ../Mysql-Master-Slave/slave-PB.yml
            #  ansible-playbook -i environment/inventory -e @vars/CreateDB-and-Restore-PB.yml CreateDB-and-Restore-PB.yml